import Head from "next/head";
import { request, gql } from "graphql-request";
import MyHeroComponent from "../components/myHero";
import { useEffect, useState } from "react";

export default function Home() {
  const [ComponentsContainer, setComponentsContainer] = useState(null);

  const query = gql`
    {
      country(code: "US") {
        name
        emoji
        emojiU
        languages {
          name
        }
      }
    }
  `;

  const GetCountry = async () => {
    return await request(
      "https://countries.trevorblades.com/graphql",
      query
    ).then((data) => {
      return (
        <MyHeroComponent
          name={data.country.name}
          emoji={data.country.emoji}
          languages={data.country.languages}
        />
      );
    });
  };

  useEffect(() => {
    GetCountry().then((country: any) => {
      return setComponentsContainer(country);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Vagaro Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="components-container-wrapper">{ComponentsContainer}</div>
    </>
  );
}
